### ISSUE TITLE
[BUG] all outputs show default branch when on a PR branch

### ISSUE THREAD

**Issue by philjones88** [tj-actions/branch-name#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Output from action even on a PR branch all relates to the default branch even when on a PR

### To Reproduce

```
name: Build

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6.2

      - name: Current branch info
        run: |
          echo "Name:     ${{ steps.branch-name.outputs.current_branch }}"
          echo "Ref:      ${{ steps.branch-name.outputs.ref_branch }}"
          echo "Head Ref: ${{ steps.branch-name.outputs.head_ref_branch }}"
          echo "Default:  ${{ steps.branch-name.outputs.is_default }}"
```

returns:

```
Name:     master
Ref:      master
Head Ref: test-pr
Default:  true
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

It to output the `current_branch` correctly and have `is_default` set to false when on a PR branch.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
