### ISSUE TITLE
[BUG] Extraction of tag doesn't work properly

### ISSUE THREAD

**Issue by JonasDoe** [tj-actions/branch-name#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When running the action with `strip_tag_prefix: true`, the tag is not extracted properly.

### To Reproduce

Take this workflow file:
```yaml
name: Publish docker image for release
on:
  release:
    types: [published]

jobs:
  generate:
    name: Create release docker image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7.0.3
        with:
          strip_tag_prefix: true
      - name: Print version
        run: echo ${DOCKER_TAG} # Prints refs/tags/v1.2.3 instead of 1.2.3
        env:
          DOCKER_TAG: ${{ steps.branch-name.outputs.tag }}
```

### What OS are you seeing the problem on?

all

### Expected behavior?

The extracted tag has the form of `refs/tags/v1.2.3`, while I expected `1.2.3`.

### Anything else?

Based on [this](https://github.com/tj-actions/branch-names/discussions/254) discussion.  @jackton1 guessed it's caused by `strip_tag_prefix: true` there.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
